[package]
name = "translate_rna_to_protein"
version = "0.1.0"
authors = ["Sean Oliver <snoliver@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
